In [ ]:
import numpy as np 
#arr = np.array([2, 4, 4, 6])
print(arr)
print(type(arr))

[2 4 4 6]
<class 'numpy.ndarray'>


In [27]:
zeros = np.zeros(5)
ones = np.ones((3, 3))
print("zeros:", zeros)
print("ones:\n", ones)

zeros: [0. 0. 0. 0. 0.]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Changing shape
big_zeros = np.zeros(10)
reshaped = big_zeros.reshape(10, 1)

print("reshaped:\n", reshaped)

reshaped:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
reshaped:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [44]:
# Empty array
empty_arr = np.empty((2, 2))
print("empty_arr:\n", empty_arr)

empty_arr:
 [[1.22680995e-315 0.00000000e+000]
 [1.22418289e-315 1.22108475e-315]]


In [46]:
# Linspace
linear = np.linspace(2, 10, 5)
print("linear:\n", linear)

linear:
 [ 2.  4.  6.  8. 10.]


zeros → creates array filled with 0
ones → creates matrix of 1s
reshape → changes shape (important for ML)
empty → fast but contains garbage values
linspace → evenly spaced numbers
array() → converts list → NumPy array
Why:
Used for initialization, simulations, ML inputs

In [51]:
# Random integers
random_arr = np.random.randint(0, 10, 5)
print("random_arr:\n", random_arr)

# Indexing and slicing
first = random_arr[0]
range_vals = random_arr[0:2]
last = random_arr[-1]

print("first:", first)
print("range:", range_vals)
print("last:", last)

random_arr:
 [1 9 8 2 7]
first: 1
range: [1 9]
last: 7


In [47]:
# From list
arr_from_list = np.array([1, 2, 3])

In [6]:
arr = np.array([[1,2,3],
                [4,5,6],
                [5,6,7]])
print(arr)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [7]:
print(arr.shape)   
print(arr.ndim)    
print(arr.size)    

(3, 3)
2
9


In [13]:
np.sum(arr, axis=0)


array([10, 13, 16])

You are summing column-wise

Calculation:
col0: 1 + 4 + 5 = 10
col1: 2 + 5 + 6 = 13
col2: 3 + 6 + 7 = 16

In [11]:
np.sum(arr, axis=1)

array([ 6, 15, 18])

You are summing row-wise

Calculation:
row0: 1 + 2 + 3 = 6
row1: 4 + 5 + 6 = 15
row2: 5 + 6 + 7 = 18

In [16]:
np.mean(arr, axis=0)
# np.mean(arr, axis=1)

array([3.33333333, 4.33333333, 5.33333333])

In [24]:
x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6],
              [7, 8]])

result = np.dot(x, y)
#result = np.matmul(x, y)#
#result = x @ y
print(result)
addition = x + y
print(addition)
subtraction = x - y
print(subtraction)
multiplication = x * 10
print(multiplication)


[[19 22]
 [43 50]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[10 20]
 [30 40]]


In [18]:
arr = np.array([1, 2, 3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


Where:

e≈2.718 (Euler’s number)
[1,  2,    3]
 ↓   ↓   ↓
[e¹, e², e³]

In [ ]:
arr = np.array([1, 2, 3])
exp_vals = np.exp(arr)
#print(exp_vals)
#print(np.sum(exp_vals))
prob = exp_vals / np.sum(exp_vals) # Softmax function use in ML/DL activations fuctions
print(prob)

[ 2.71828183  7.3890561  20.08553692]
30.19287485057736
[0.09003057 0.24472847 0.66524096]


In [8]:
import cv2

# Load image
photo = cv2.imread("chironto_paul.png")

print("Shape:", photo.shape)

ModuleNotFoundError: No module named 'cv2'